### ISSUE TITLE
Compiling error on Ubuntu 20.04: Invalid Account Type

### ISSUE THREAD

**Issue by Znote** [opentibiabr/otservbr-global-archived#1328]
GNU 9.3.0
Ubuntu 20.04
Commit: (Latest at this moment):
[b94a78b6d96b23e7f6bf54c4dd00df11318569d6](https://github.com/opentibiabr/otservbr-global/tree/b94a78b6d96b23e7f6bf54c4dd00df11318569d6)

Instructions followed: (Wiki - Compiling on Ubuntu)
https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu

![image](https://user-images.githubusercontent.com/1552144/84315360-d9ab0100-ab69-11ea-98d3-3f4220a9eb5b.png)

```bash
stefsien@freeuse:~/otbr/github$ cd build
stefsien@freeuse:~/otbr/github/build$ cmake ..
CMake Warning (dev) at cmake/FindCryptoPP.cmake:73 (SET):
  implicitly converting 'DOC' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:60 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so;-ldl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stefsien/otbr/github/build
stefsien@freeuse:~/otbr/github/build$ make -j`nproc`
[  1%] Checking the git repository for changes...
[  1%] Built target check_git
Scanning dependencies of target otbr
[  2%] Building CXX object CMakeFiles/otbr.dir/src/otpch.cpp.o
[  3%] Building CXX object CMakeFiles/otbr.dir/src/account.cpp.o
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/github/src/account.cpp:23:
/home/stefsien/otbr/github/src/account.cpp: In member function ‘error_t account::Account::SetAccountType(account::AccountType)’:
/home/stefsien/otbr/github/src/account.cpp:412:18: error: too many arguments for format [-Werror=format-extra-args]
  412 |     LOG_F(ERROR, "Invalid Account Type!", static_cast<int>(account_type));
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/otbr.dir/build.make:76: CMakeFiles/otbr.dir/src/account.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/otbr.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
stefsien@freeuse:~/otbr/github/build$ git log -1
commit b94a78b6d96b23e7f6bf54c4dd00df11318569d6 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Gabriel Pedro <gpedro@users.noreply.github.com>
Date:   Tue Jun 9 23:06:25 2020 -0400

    Fix aleta grav on closed door (#1103)

    * Fix aleta grav on closed door

    Co-authored-by: Sarah Wesker <sarahelizabetwesker@gmail.com>
stefsien@freeuse:~/otbr/github/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
stefsien@freeuse:~/otbr/github/build$
```

**Comment by lurkgabriel** [comment]
as far as I can tell there's no support for unbutu 20 just yet, you'll have to rollback to ubuntu 18 unfortunately (a guy was trying this a few days ago and reached us trhough discord). also, thank you for your znote website it helped me a lot ;)

**Comment by Costallat** [comment]
I will fix that, but I don't know if the compilation will work on Ubuntu 20.04, I need to check some flags because it complains about the conversions made to print the log.

**Comment by Costallat** [comment]
@Znote can you check if #1330 solve this problem? Tks

**Comment by Znote** [comment]
Fixed in #1330
